{"name": "Проверка логина с неверными данными", "status": "passed", "steps": [{"name": "Генерирует случайного пользователя", "status": "passed", "start": 1730114401677, "stop": 1730114401677}, {"name": "Логинит пользователя через API", "status": "passed", "parameters": [{"name": "user", "value": "<helpers.User object at 0x000001B14D2E3B60>"}], "start": 1730114401677, "stop": 1730114402100}], "start": 1730114401677, "stop": 1730114402100, "uuid": "416baaa6-49a7-4284-9e10-21c49951019a", "historyId": "8f90415445626d367e3fa6e965f85875", "testCaseId": "8f90415445626d367e3fa6e965f85875", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "20504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}