{"name": "Проверка логина с неверными данными", "status": "passed", "start": 1729622448422, "stop": 1729622448733, "uuid": "02c5ebff-dac6-4d10-8287-9ae4b0717334", "historyId": "8f90415445626d367e3fa6e965f85875", "testCaseId": "8f90415445626d367e3fa6e965f85875", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "10652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}